### PR TITLE
[BUGS-5122] Push missing tags on wordpress project.

### PR DESCRIPTION
**Pull request by kporras07**
### Overview
This pull request will add a new command to push missing tags on a regular basis.

### Summary
Adds new project:upstream:push-tags command.

### CODE REVIEW

**Comment by CdrMarks** [comment]
@kporras07 will there be an additional PR on updatinator to run the `push-tags` command?

**Comment by kporras07** [comment]
Yup, there will be. I'll create it later today

**Comment by CdrMarks** [comment]
@kporras07 Have you been able to test this?  If so, how?

**Comment by kporras07** [comment]
@CdrMarks yes, in my local env using --dry-run (the only omitted step is pushing the tag)

You can check out the logs in the Jira ticket

**Review by CdrMarks — APPROVED** [review]
LGTM after review the code and logs.

**Pull request merged**
